name: CI
on: [push]
jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: npm ci
      - name: cache
        uses: actions/cache@v3
        with:
          key: npm-${{hashfiles('package-lock.json')}}
          path: ~/.npm

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint

  test-unit:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: npm ci
      - name: test
        run: npm run test.unit

  test-functional:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: npm ci
      - name: run Cypress
        uses: cypress-io/github-action@v4
        with:
          command: npm run test.fxn
          start: npm run start.ci -- --port 3000
          wait-on: http://localhost:3000
          wait-on-timeout: 20
        env:
          CYPRESS_BASE_URL: http://localhost:3000
          DEBUG: '@cypress/github-action'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
